### ISSUE TITLE
pip version missing soco.music_services

### ISSUE THREAD

**Issue by Zolmeister** [SoCo/SoCo#427] opened 2016-08-30 18:57 UTC
python 3.5
```python
import soco.music_services
```
fails from pip install
Installing from source (master) works

**Comment by KennethNielsen** [comment] 2016-09-05 20:50
Hallo @Zolmeister 

The universal music_services code was not merged yet at the time of the last release. To use it from pypi you will have to wait for the next release (which have been way to long in the making). You can follow the progress here #315.

I'll close this as it is not a bug.

Regards Kenneth

**Closed by KennethNielsen** 2016-09-05 20:50 UTC
