### ISSUE TITLE
Communication with Sonos stops after a few days of connection

### ISSUE THREAD

**Issue by siegeld** [SoCo/SoCo#295] opened 2015-02-23 18:30 UTC
Please see the log info below.  After a while, I get Errno 32, and all further SoCo commands to the Sonos seem to have no effect, though I get no additional errors.  Suggestions?

    2015-02-23 07:39:21,032 - INFO - services - Sending GetPositionInfo [(u'InstanceID', 0), (u'Channel', u'Master')] to 192.168.71.49
    2015-02-23 07:39:21,036 - INFO - connectionpool - Starting new HTTP connection (1): 192.168.71.49
    Traceback (most recent call last):
       File "/usr/lib64/python2.7/SocketServer.py", line 582, in process_request_thread
          self.finish_request(request, client_address)
       File "/usr/lib64/python2.7/SocketServer.py", line 323, in finish_request
          self.RequestHandlerClass(request, client_address, self)
       File "/usr/lib64/python2.7/SocketServer.py", line 640, in __init__
          self.finish()
       File "/usr/lib64/python2.7/SocketServer.py", line 693, in finish
          self.wfile.flush()
       File "/usr/lib64/python2.7/socket.py", line 303, in flush
          self._sock.sendall(view[write_offset:write_offset+buffer_size])
    error: [Errno 32] Broken pipe
    2015-02-23 07:39:21,046 - INFO - services - Received status 200 from 192.168.71.49

**Comment by KennethNielsen** [comment] 2015-06-06 09:57
Hallo @siegeld 

Thanks for reporting this.

Sorry about the long reply time, it seems most of the dev team is busy with real life at the moment.

If you are still interested in having this fixed and is willing to do some testing please let me know and I will try to help. The problem is, that this sounds like a connection timeout issue somewhere, but the stack cnsists of SoCo - requests - some_form_of_urllib_i_guess, socket, operating system socket and eventually the Sonos units them selves, so it may be a little tricky to find.

A few questions before we start. Have you reproduced it (I have to ask, just to make sure this was not simply a bump on your local network).

Have you already tried to see if you can keep it alive by sending a small request say once every hour?

Regards Kenneth

**Comment by KennethNielsen** [comment] 2015-07-29 11:37
It has been a while now without any activity in this (but we were of course also very slow to answer in the first place). I will close it for now. @siegeld if you find time to reply and help us follow up on the cause of this, please just re-open the issue.

**Closed by KennethNielsen** 2015-07-29 11:37 UTC
Labels: bug, Needs info
