### ISSUE TITLE
Event listener memory leak?

### ISSUE THREAD

**Issue by pfischi** [SoCo/SoCo#653] opened 2018-12-18 20:15 UTC
Following the given Event Listener [example](http://docs.python-soco.com/en/latest/api/soco.events.html), the used memory is constantly growing.

Steps to repeat:

1. Run event listener example from link.
2. Use "psrecord" (or similiar tools) and attach to the started process above and capture the memory consumption
3. Within the Sonos App, trigger some events (Play, Pause, another title etc)
4. After each event, the used memory grows constantly
5. The option "soco.config.CACHE_ENABLED = False" has no effect to this issue

Thanks for your great work,

Stefan

**Comment by aschwith** [comment] 2019-05-06 17:47
Can anyone confirm the memory leak of the event listener? This issue might be worth fixing for release 0.17 too.

**Comment by KennethNielsen** [comment] 2019-10-11 12:48
Second, I can see that @aschwith tagged this as the potential source of an error in https://github.com/smarthomeNG/smarthome/issues/312, but it then in that thread seems to be exonerated. So my questions is if that problem was the reason @pfischi measured this to begin with. I.e. if this has caused a real world problem.

**Comment by aschwith** [comment] 2019-10-11 14:19
Hi @KennethNielsen, thanks for getting back to us. Actually, @pfischi and myself have been working on the same smarthomeNG project which uses the SoCo framework to control Sonos devices. I am not sure if @pfischi is still online but I can confirm that unfortunately the memory leak still exists with with SoCo 0.17.

We were testing similar to the way that you suggested. @pfischi described how we reproduce it. 
Is there a maximum size for the event queues or will the keep on increasing forever? I will try to add the debug output as you suggested to see if the queues are emptied properly. 
Also, I wonder if you or someone else here in the SoCo community can confirm the memory leak in the environment they are using?

**Comment by aschwith** [comment] 2019-10-11 14:31
@KennethNielsen can you recommend a suitable debug output to monitor the event queue? Thanks a lot.

**Comment by KennethNielsen** [comment] 2019-10-20 13:40
@aschwith ok, let's do one thing at a time. First of, can I get you to clarify whether I read that smarthomeNG thread correctly in that the bug described there was not related to SoCo? I would like to first determine whether a bug has been observed in the wild, or only in a synthetic test.

**Comment by KennethNielsen** [comment] 2019-10-20 13:42
Second, can you please post the test code you use. That is always a good starting point. I aware that as @pfischi mentioned, it is probably close to the code in the event module docstring, but it be nice with the exact code so that we are sure we are talking about the same thing.

I hope you are ok with doing a little bit of the leg work on this one, as my time to spend on SoCo is unfortunately not too much.

**Comment by aschwith** [comment] 2019-10-20 18:13
Hi @KennethNielsen , yes I can confirm that the smarthomeNG thread was not related to SoCo at the end. However, the memory leak is observable for everyone who uses SmarthomeNG in combination with the enabled Sonos plugin which is based on SoCo. 
I am able to reproduce the memory leak issue within the smarthomeNG environment. @pfischi was able to reproduce the same issue with the SoCo minimal exampe code from the event listener. Therefore, it should be straight forward in the community to confirm. I started to add debug outputs attached to the event queue to monitor if the number of events increases but could not observe anything special so far. Any suggestion or confirmation of the memory leak is highly appreciated.

**Comment by KennethNielsen** [comment] 2019-11-03 15:31
Ok. So I have tried to reproduce this within SoCo and I have been unable to reproduce any serious memory leak. When I write serious it is because I find i difficult to figure out what I should have observed. Keep in mind that this is not like memory profiling a C-program, where you are certain that every single increase in memory used is something allocated by the programmer. Python, I assume, does a bunch of advanced optimizations with pro-allocation and such that means that it is not possibly to directly track and increase in memory consumption to the creation of a new object.

A further difficulty is that memory on my system is allocated in 4k pages and the event XML is maybe a few hundred bytes and maybe the same for he XML objects and so on. Bottom line is that you need to be able to create quite a few events to easily see an effect and I was simply not able to. I subscribed to all the event subscriptions and tried to script interaction like play and pause and play list changes, but all in all it didn't amount to that many events.

The bottom line from testing is that I ran a test program over about 12 hours, which is a slightly expanded version of the events example, and I was able to observe only a small increase in total memory footprint, that is small enough that I'm not convinced it doesn't just come from Python caching something before it eventually clears it up. The test data was:

```text
#events  Memory/kb
1051     25352
1619     25372
1722     26260
```
and I will post the test script at the end of this post.

Ok. So I will close this issue now. Feel free to re-open if you still think there is a problem in SoCo itself. But in order for me to spend more time on it I would need the following:

1) The exact code used **posted**
2) Steps to reproduce **with details**. It was really nice of @pfischi to post steps to reproduce, but I was unable to use some of them e.g. I was unable to figure out how to change units in psrecord from MB to KB.
3) Example output that shows the leak


The script used was:
```python

from time import sleep

from threading import Thread

from pprint import pprint
from queue import Empty
from soco.discovery import by_name
from soco import events
from soco.events import event_listener

device = by_name("Køkken")

subs = []
for service in (device.avTransport, device.contentDirectory,
                device.deviceProperties, device.renderingControl,
                device.zoneGroupTopology, device.alarmClock,
                device.systemProperties,
                device.musicServices):
    subs.append(service.subscribe())


def switch():
    last = 1
    while True:
        sleep(0.1)
        last = (last + 1) % 2
        device.play_from_queue(last)
        device.volume = last + 1


Thread(target=switch, daemon=True).start()

event_num = 0
wait = 0.01
while True:
    size = 0
    try:
        for sub in subs:
            try:
                event = sub.events.get(timeout=wait)
                event_num += 1
                pprint(event.variables)
            except Empty:
                pass
            #pprint(event.variables)
            size += sub.events.qsize()

    except KeyboardInterrupt:
        for sub in subs:
            sub.unsubscribe()
        event_listener.stop()
        break

    print("Events", event_num, "Q size", size)
```

**Closed by KennethNielsen** 2019-11-03 15:31 UTC
