### ISSUE TITLE
Unable to add Queue item to queue

### ISSUE THREAD

**Issue by robwebset** [SoCo/SoCo#223] opened 2014-09-13 08:02 UTC
I've noticed that if you do a get_queue it returns to a List of Queue items.

However you can not use these items to then pass into add_to_queue.

Instead you have to extract the URI from the object and pass it into add_uri_to_queue.

This seems a little odd - I guess ideally add_to_queue would be able to take any of the queue type objects (QueueItem, Queue).

With this in mind, is it possible to add multiple items to a queue in a single request?

**Comment by ghcs27** [comment] 2017-01-14 10:29
I'll have a go at it.

**Comment by KennethNielsen** [comment] 2017-03-13 21:23
Thanks to @ghcs27 this is now possible via #470. The add_multiple_to_queue takes any sequence of queueable items (and therefore also a queue) as an argument. I do however think I have hit a bug with it, so don't go rewrite snapshot just yet.

However, given that it should now be possible, I'll close this. Feel free to re-open if you don't thinks the issue is resolved.

**Closed by KennethNielsen** 2017-03-13 21:23 UTC

**Comment by KennethNielsen** [comment] 2017-03-13 22:10
#485 for reference.
