### ISSUE TITLE
soco.discover() broken under Python 3.4.2

### ISSUE THREAD

**Issue by rtkwgray** [SoCo/SoCo#298] opened 2015-03-28 21:22 UTC
I'm seeing an exception when trying to use soco.discover() under Python 3.4.2. Please see the following script:

```python
import soco
import sys
print(sys.version)
soco.discover()
```

This results in the following:
```
3.4.2 (v3.4.2:ab2c023a9432, Oct  5 2014, 20:42:22) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]
Traceback (most recent call last):
  File "/Users/wgray/soco.py", line 4, in <module>
    soco.discover()
  File "/Users/wgray/python34/lib/python3.4/site-packages/soco/core.py", line 100, in discover
    if "Sonos" not in data:
TypeError: Type str doesn't support the buffer API
```

**Comment by KennethNielsen** [comment] 2015-04-01 15:32
Hallo @rtkwgray and thanks for your report.

I can see that upstream the code has changed to this: https://github.com/SoCo/SoCo/blob/master/soco/discovery.py#L128 which I assumes fixes this. It would be helpful, if you could test if git master works for you, to see if it does indeed fix it. If it does, then you can keep using git master or wait for next release (which hopefully wont be that far into the future).

**Comment by KennethNielsen** [comment] 2015-04-01 15:37
Ahh, I dug a bit, and as it turns out, this a duplicate of https://github.com/SoCo/SoCo/issues/271. So I'll assume it is fixed and close this. If the issue persist after next release, feel free to re-open.

**Closed** 2015-04-01 15:38 UTC
Labels: bug, duplicate
