### ISSUE TITLE
discover() socket error

### ISSUE THREAD

**Issue by stu247** [SoCo/SoCo#449] opened 2016-11-19 21:49 UTC
When running soco.discover(), I get an error. 

I installed Python 2.7.12 on Windows 10.  Then I ran `pip install soco`.  This installed SoCo 0.12.  I then ran the following:

`
C:\Python27\Lib>python
Python 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:19:22) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import soco
>>> soco.discover()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\soco\discovery.py", line 123, in discover
    list(s.getsockname()[0] for s in _sockets))
  File "C:\Python27\lib\site-packages\soco\discovery.py", line 123, in <genexpr>
    list(s.getsockname()[0] for s in _sockets))
  File "socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 10022] An invalid argument was supplied
>>>
`

**Comment by lawrenceakka** [comment] 2016-11-20 08:29
Thanks for the report. It looks like this is the same as #445, which has just been fixed in the development version. Are you able to try the most up-to-date checkout from GitHub? I'll mark as closed for now, but please re-open if you continue to have problems.

**Closed by lawrenceakka** 2016-11-20 08:29 UTC

**Comment by msanecki** [comment] 2016-11-20 15:44
I am not familiar with pythin but I downloaded the master repo
executest setup.py build then setup.py install
Here is the last output (everything looks fine)

Installed c:\python27\lib\site-packages\soco-0.12-py2.7.egg
Processing dependencies for soco==0.12
Searching for xmltodict==0.10.2
Best match: xmltodict 0.10.2
Adding xmltodict 0.10.2 to easy-install.pth file

Using c:\python27\lib\site-packages
Searching for requests==2.12.1
Best match: requests 2.12.1
Adding requests 2.12.1 to easy-install.pth file

Using c:\python27\lib\site-packages
Finished processing dependencies for soco==0.12

**Then I executed the spl.py again, the bug seems stil be there.** 

C:\Users\User\Downloads\spl>spl.py
Traceback (most recent call last):
  File "C:\Users\User\Downloads\spl\spl.py", line 446, in <module>
    spl = SPL()
  File "C:\Users\User\Downloads\spl\spl.py", line 260, in __init__
    zones = soco.discover()
  File "build\bdist.win32\egg\soco\discovery.py", line 123, in discover
  File "build\bdist.win32\egg\soco\discovery.py", line 123, in <genexpr>
  File "C:\Python27\lib\socket.py", line 228, in meth
    return getattr(self._sock,name)(*args) E
socket.error: [Errno 10022] An invalid argument was supplied

**Comment by lawrenceakka** [comment] 2016-11-20 15:56
Hi Marcin,

Where did you download from? If you downloaded a release version, that is  the same as the one you got from pypi. You actually need the development version, which you can get by using git, or by using the green "clone or download" button on the repository front page.  

Note, you don't need to use ```setup.py build```, only ```setup.py install```

**Comment by msanecki** [comment] 2016-11-20 16:05
My mistake I took the release 0.12 version from https://pypi.python.org/pypi/soco/
So now I am getting the real master version 0.11.1 and with this version I cannot reproduce the bug. 

Thanks @lawrenceakka.

**Comment by msanecki** [comment] 2016-11-24 20:07
After installing the master branch version by executing this command
`setup.py install`

The soco package is labeled with 0.11.1 but the latest releast version is 0.12.
```
C:\python2.7\Scripts>pip list
pip (8.1.1)
requests (2.12.1)
setuptools (20.10.1)
soco (0.11.1)
xmltodict (0.10.2)
```
Is the master branch version really 0.11.1 or 0.12.x ? Maybe I did something wrong during intallation from sources.

**Comment by JochenPfeifferHD** [comment] 2017-03-12 11:23
hi i get the same error. i downloaded the master branch (Version 0.11.1) and executed "Setup.py isntall" and pip install requests.
Any news to this issue?

**Comment by KennethNielsen** [comment] 2017-03-13 20:51
I think someone forgot to update the version string after last release. I have now changed it to say "0.12+", so that it will be possible to infer development status from the version string alone.

From what I can gather from the comments, this issue **is** resolved in the development version, so it is just about waiting for the next release. You can follow the discussion surrounding that here #442.
