### ISSUE TITLE
Spotify Plugin is broken

### ISSUE THREAD

**Issue by gregmankes** [SoCo/SoCo#424] opened 2016-08-23 00:09 UTC
```
from soco import SoCo
from soco.plugins.spotify import Spotify, SpotifyAlbum
spotify = Spotify(SoCo('192.168.1.146'))
spotify_album = SpotifyAlbum('spotify:album:3gqiTbYCXF9p10eUbfqRLj')
spotify.add_album_to_queue(spotify_album)
# JSONDecodeError: No JSON object could be decoded: line 1 column 0 (char 0)
```

I believe that this is due to soco.plugins.spotify.Spotify's api_plugin_url is deprecated. Going to the link http://ws.spotify.com/lookup/1/.json returns `This API has been deprecated. Please upgrade to our new APIs: https://developer.spotify.com/web-api/migration-guide/`

**Comment by KennethNielsen** [comment] 2016-08-23 13:45
Hallo @gregmankes 

This is a known issue (see #401). As you mention, the API that the plugin uses has been deprecated and we now have more general code in the music service sub package to interface with all the music services.

I already proposed to deprecate the plugin #423.

I'll close this now as a duplicate of #401. If you need info on how to use the new music service code, see the deprecation text string in #423 for sources.

Thanks for reporting this.

**Closed by KennethNielsen** 2016-08-23 13:45 UTC
