### ISSUE TITLE
get_current_track_info: ParseError: not well-formed (invalid token)

### ISSUE THREAD

**Issue by ArjanM83** [SoCo/SoCo#386] opened 2016-03-06 11:41 UTC
When requesting current track info, this results in an error when an invalid token is returned by the sonos zone:

```
  File "C:\Python27\lib\site-packages\soco\core.py", line 1019, in get_current_t
rack_info
    ('Channel', 'Master')
  File "C:\Python27\lib\site-packages\soco\services.py", line 156, in _dispatche
r
    return self.send_command(action, *args, **kwargs)
  File "C:\Python27\lib\site-packages\soco\services.py", line 351, in send_comma
nd
    result = self.unwrap_arguments(response.text) or True
  File "C:\Python27\lib\site-packages\soco\services.py", line 244, in unwrap_arg
uments
    tree = XML.fromstring(xml_response)
  File "<string>", line 124, in XML
ParseError: not well-formed (invalid token): line 1, column 850
```

This is the xml_response, I believe the invalid content is within the stream content:

```
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle=
"http://schemas.xmlsoap.org/soap/encoding/"><s:Body><u:GetTransportInfoResponse
xmlns:u="urn:schemas-upnp-org:service:AVTransport:1"><CurrentTransportState>PLAY
ING</CurrentTransportState><CurrentTransportStatus>OK</CurrentTransportStatus><C
urrentSpeed>1</CurrentSpeed></u:GetTransportInfoResponse></s:Body></s:Envelope>
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle=
"http://schemas.xmlsoap.org/soap/encoding/"><s:Body><u:GetPositionInfoResponse x
mlns:u="urn:schemas-upnp-org:service:AVTransport:1"><Track>1</Track><TrackDurati
on>0:00:00</TrackDuration><TrackMetaData>&lt;DIDL-Lite xmlns:dc=&quot;http://pur
l.org/dc/elements/1.1/&quot; xmlns:upnp=&quot;urn:schemas-upnp-org:metadata-1-0/
upnp/&quot; xmlns:r=&quot;urn:schemas-rinconnetworks-com:metadata-1-0/&quot; xml
ns=&quot;urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/&quot;&gt;&lt;item id=&quot
;-1&quot; parentID=&quot;-1&quot; restricted=&quot;true&quot;&gt;&lt;res protoco
lInfo=&quot;x-rincon-mp3radio:*:*:*&quot;&gt;x-rincon-mp3radio://icecast-qmusic.
cdp.triple-it.nl/Qmusic_nl_nonstop_96.mp3&lt;/res&gt;&lt;r:streamContent&gt;Stol
e The Show - KYGO &amp;amp; PARSON JAMES&amp;apos;♣&lt;/r:streamContent&gt;&lt;d
c:title&gt;Qmusic_nl_nonstop_96.mp3&lt;/dc:title&gt;&lt;upnp:class&gt;object.ite
m&lt;/upnp:class&gt;&lt;/item&gt;&lt;/DIDL-Lite&gt;</TrackMetaData><TrackURI>x-r
incon-mp3radio://icecast-qmusic.cdp.triple-it.nl/Qmusic_nl_nonstop_96.mp3</Track
URI><RelTime>0:00:03</RelTime><AbsTime>NOT_IMPLEMENTED</AbsTime><RelCount>214748
3647</RelCount><AbsCount>2147483647</AbsCount></u:GetPositionInfoResponse></s:Bo
dy></s:Envelope>
```

**Comment by KennethNielsen** [comment] 2016-04-12 18:29
Hi @ArjanM83 and thanks for reporting this.

Can you please post the repr version of the XML response? Also, does this happen to you often or only with a specific track?

**Comment by ArjanM83** [comment] 2016-04-13 09:44
Hi @KennethNielsen,

Can you explain how I could get the repr version of the XML response?

I'm running a discovery script every minute to monitor the status of my Sonos speakers and to see if/what they're playing. Often, I'm playing a radio stream. When there's a song on the radio with invalid characters in its name, this error occurs. So it depends on the DJ of the radio station.

It's not easy to reproduce the error for me, so I hope the current explanation will do.

**Comment by KennethNielsen** [comment] 2016-04-14 18:11
@ArjanM83 Are you fairly familiar with git? I.e. would you be able to run of a branch of mine if I create one that outputs some more debugging information?

**Comment by ArjanM83** [comment] 2016-04-15 09:57
Hi @KennethNielsen,

Sure, I think that would be possible. But could you have the debug information written to a file, using a path defined by me? I'm using SoCo in my home automation solution to control my speakers and would rather not break it. My solution is working around this error by ignoring the errors.

The error is not easily reproducible, it could take a while before a track is played with an erroneous character in its name. If it's convenient for you, you could try to play the internet radio station yourself. I've looked up the uri of the internet radio causing these errors.

`x-rincon-mp3radio://icecast-qmusic.cdp.triple-it.nl/Qmusic_nl_nonstop_96.mp3`

For this radio station, almost every track title shows strange characters at the end, but only some of these characters cause the error. This is one example track dict, notice the **title**:

```python
{u'album': u'', u'artist': u'Freedom', u'title': u"PHARRELL WILLIAMS'wfYG \xb1bp\x81\x81", u'uri': 'x-rincon-mp3radio://icecast-qmusic.cdp.triple-it.nl/Qmusic_nl_nonstop_96.mp3', u'playlist_position': '1', u'duration': '0:00:00', u'position': '0:01:51', u'album_art': u'', u'metadata': u'<DIDL-Lite xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:upnp="urn:schemas-upnp-org:metadata-1-0/upnp/" xmlns:r="urn:schemas-rinconnetworks-com:metadata-1-0/" xmlns="urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/"><item id="-1" parentID="-1" restricted="true"><res protocolInfo="x-rincon-mp3radio:*:*:*">x-rincon-mp3radio://icecast-qmusic.cdp.triple-it.nl/Qmusic_nl_nonstop_96.mp3</res><r:streamContent>Freedom - PHARRELL WILLIAMS&apos;wfYG \xb1bp\x81\x81</r:streamContent><dc:title>Qmusic_nl_nonstop_96.mp3</dc:title><upnp:class>object.item</upnp:class></item></DIDL-Lite>'}
```

**Comment by KennethNielsen** [comment] 2016-04-15 19:09
@ArjanM83 Yeah, I think I could write it up like that. I dont' really have time to troubleshoot it myself.

This is kind if annoying, it definitely looks like and character encoding error, but looking at the implementation, I can't spot any obvious mistakes.

I did notice that the line numbers are of so I guess that you are using a released version. Could I get you to check whether the error is also there in the master branch here in development?

**Comment by KennethNielsen** [comment] 2016-04-15 19:53
@ArjanM83 on second thought, hold of on checking master. I don't think that will solve it.

**Comment by KennethNielsen** [comment] 2016-04-15 20:17
Hmm. After a lot of banging my head against the XML spec, concerning valid chars etc. I realized that the chunk of XML you pasted has two toplevel tags in it (it is essentially two XML documents). You can tell in that the Elevelope tag that opens the whole thing is closed and the a new one opens. If I delete one of the two, the XML parses just fine, weird characters and all. Now the questions is, do we really get a payload with two elements in it. How did you get this samples of XML?

**Comment by ArjanM83** [comment] 2016-04-16 09:12
@KennethNielsen When I was searching for a reason for these errors, I inserted a print statement in the unwrap_arguments function. I copied the last part of the data retrieved into this issue, and must have accidentely copied the last two parts.

I will look into this again and try to add some more usefull information.

**Comment by KennethNielsen** [comment] 2016-04-16 09:38
@ArjanM83 Yes. I guess that could be what had happened. If we are to get to the bottom of this, without interrupting operation of you application to much, what we could do is to ask it to output to a file only when the error occurs. I think, that if you change the XML parsing bit in unwrap_arguments to something like this:

```python
        # Get all tags in order. Elementree (in python 2.x) seems to prefer to
        # be fed bytes, rather than unicode
        xml_response = xml_response.encode('utf-8')
        try:
            tree = XML.fromstring(xml_response)
        except Exception:
            import codecs
            with codecs.open('debug_file', 'w', 'utf-8') as file_:
                file_.write(xml_response.decode('utf-8'))
            raise
```

I think that should leave us the last xml_response that failed to parse in 'debug_file', which you can then attach (not paste) to this issue. Thanks.

**Comment by ArjanM83** [comment] 2016-04-16 13:27
@KennethNielsen I've used your code to create the debug file. I started the online radio station this morning and already got 10+ errors. See the attached text file for more details.

[sonos_debug.txt](https://github.com/SoCo/SoCo/files/222203/sonos_debug.txt)

**Comment by KennethNielsen** [comment] 2016-04-16 19:47
@ArjanM83 Ok. I think I have found the cause now. It seems that this radio station **is** sending "illegal" characters in the XML. In this case it was a Ctrl-d (code point 0x04) character. Stripping illegal characters out before trying to parse it makes it succeed.

There are just a few more things I need to understand and then I can start working on a fix.

**Comment by KennethNielsen** [comment] 2016-04-17 06:23
@ArjanM83 Can you test the filter_invalid_chars_in_xml_fixes branch from my repository: https://github.com/KennethNielsen/SoCo ?

**Comment by ArjanM83** [comment] 2016-04-17 09:36
@KennethNielsen thank you for your work, I will use the branch and run the discovery for a day to see if everything works fine.

**Comment by ArjanM83** [comment] 2016-04-18 16:43
@KennethNielsen The discovery process has run over a day and has not experienced any error. Although the test case is not 100% reliable (the web radio could have had one day without sending errors), I would say this issue is solved.

Thanks again for your work.

**Comment by KennethNielsen** [comment] 2016-04-19 18:59
@ArjanM83 No problem - Its always fun to work on one that I can figure out ;)

I'm just going to leave the issue open until the fix is integrated in main.

Thanks for reporting.

**Closed** 2016-05-02 20:33 UTC
