### ISSUE TITLE
discover() returning None

### ISSUE THREAD

**Issue by kberg** [SoCo/SoCo#384] opened 2016-02-06 17:14 UTC
This is running from a Mac Pro which can control the Sonos using the Mac app no problem.

> > > logging.basicConfig(level=logging.DEBUG)
> > > print soco.discover()
> > > INFO:soco.discovery:Sending discovery packets
> > > None

When I first downloaded the python module, it worked great. Now, nothing. I have no idea why.

(Also if I could find a mailing list, I'd raise this question there rather than in an issue.)

**Comment by kberg** [comment] 2016-02-07 22:05
Looks like soco.SoCo(ip) still works. So I may change my code to be resilient enough to fall back on historical IPs rather than trying to discover the network.

**Comment by robwebset** [comment] 2016-02-08 05:38
I believe I did a pull request for this one:

https://github.com/SoCo/SoCo/pull/289

Should improve discovery

**Comment by DPH** [comment] 2016-02-08 08:43
I use the following - which takes some time, but does eventually work. 
```
while not zones:
    print('looking...')
    zones = soco.discover(timeout=5)
```

As @robwebset says there is an enhancement for machines that have multiple interfaces, which allows you to specify the interface:
```
zones = soco.discover(timeout=5, interface_addr='192.168.0.77') 
```

This works as fast as the previous discover, if not faster.
I guess my while loop approach keeps trying and eventually hits the right interface!
The only problem with specifying interface_addr is you need to find it's IP. I'm using the IP of my machine that works, but that is hard to find programmatically.

Cheers David

**Comment by kberg** [comment] 2016-02-14 19:28
Thanks. I tried Rob's new code, but it didn't do anything for me. The IP of my local machine also didn't work. So, this is a bit of a surprise. I tried (for the first time) to grab network traffic from my machine from both my sample python and Sonos itself, and can't really tell if the broadcasts worked.

Retries also don't seem to work.

**Comment by pmatos** [comment] 2016-04-26 08:25
Same problem here, `soco.discover()` always returns `None` even with a timeout of 5.
Is there a good way to debug this kind of problem?

**Comment by pmatos** [comment] 2016-04-27 19:33
Actually the pip version fails to `discover` but using code straight from `master` works fine.

Off topic but is there a mailing list for this?

**Comment by KennethNielsen** [comment] 2016-05-05 10:10
@pmatos We have a google group: https://groups.google.com/forum/#!forum/python-soco

**Comment by KennethNielsen** [comment] 2016-05-05 10:13
@kberg If @robwebset code doesn't work for you, then I think we need to consider that this might be a different issue. But could we wait until the discussion around the more aggressive discover methods have settled (#289, #292) and the changes merged and then dive into your problem?

**Comment by lawrenceakka** [comment] 2016-05-11 16:00
The changes have now been merged (see #395). @kberg - can you try with this code? If you still have problems, let us know, otherwise we will close this issue shortly.

**Comment by marcelser** [comment] 2016-05-30 10:43
Having the same problem here. I'm not familiar with python but had soco 0.11.1 install through pip working perfectly. All of a sudden discover stopped working returning 'None' although I did not change soco version (maybe new python version?). I only have one network interface but I though let's try github version and tried to install latest version by cloning github repo locally and running python setup.py install (which seemed to run fine). But it seems the discover method doesn't accept a 'interface_addr' parameter. So I'm unsure if setup.py install correctly updated 0.11.1 installed through pip to latest master from github although it seemed to install fine:

Copying soco-0.11.1-py3.4.egg to /usr/lib64/python3.4/site-packages
Adding soco 0.11.1 to easy-install.pth file
Installed /usr/lib64/python3.4/site-packages/soco-0.11.1-py3.4.egg

Does anyone have an idea of what I've done wrong or why all of a sudden without hardware changes or updating soco library it stopped working?

**Comment by lawrenceakka** [comment] 2016-05-30 10:47
@marcelser discover definitely does accept an `interface_addr` parameter - it's there in the code!  What exactly are you doing, and what error message are you getting?  If you post the code you are trying, we can help.

**Comment by marcelser** [comment] 2016-05-30 10:57
The code starts like this and always worked (but now returns 'None' for speakers)
`#!/usr/bin/python

verbose = 1

from pprint import pprint
import soco
import sys

if len(sys.argv) == 2:
        if sys.argv[1] == '--silent':
                verbose = 0
        else:
                print ("illegal, argument, only valid argument is --silent")
                sys.exit(2)
elif len(sys.argv) > 2:
        print ("too many arguments, only valid argument is --silent")
        sys.exit(2)

print('scanning for devices')
speakers = soco.discover(timeout=5)

pprint(speakers);
`
If I change the discover line to 
`speakers = soco.discover(timeout=5, interface_addr='192.168.10.50')`

it errors like with this:
`scanning for devices
Traceback (most recent call last):
  File "./sonos_maintain_group.py", line 21, in <module>
    speakers = soco.discover(timeout=5, interface_addr='192.168.10.50')
  File "/usr/lib64/python3.4/site-packages/soco-0.11.1-py3.4.egg/soco/discovery.py", line 99, in discover
IndexError: list assignment index out of range`

therefore I'm unsure if the version installed was correctly updated with latest code from github master.

**Comment by lawrenceakka** [comment] 2016-05-30 11:13
OK - I can see a bug [here](https://github.com/SoCo/SoCo/blob/master/soco/discovery.py#L99). Can you edit the file at /usr/lib64/python3.4/site-packages/soco-0.11.1-py3.4.egg/soco/discovery.py so that line 99 says 

```python
 _sockets.append(create_socket(interface_addr))
```

instead of 

```python 
 _sockets[0] = create_socket(interface_addr)
```

Does that help?

**Comment by marcelser** [comment] 2016-05-30 13:15
Well,

thanks for your help. But now it breaks here:
scanning for devices
Traceback (most recent call last):
   File "./sonos_maintain_group.py", line 21, in <module>
     speakers = soco.discover(timeout=5, interface_addr="192.168.10.50")
   File 
"/usr/lib64/python3.4/site-packages/soco-0.11.1-py3.4.egg/soco/discovery.py", 
line 120, in discover
UnboundLocalError: local variable 'addresses' referenced before assignment

Regards,

Marc

PS: the file 
/usr/lib64/python3.4/site-packages/soco-0.11.1-py3.4.egg/soco/discovery.py 
does not exist because it's compiled in soco-0.11.1-py3.4.egg. But as I 
have downloaded the github sources I modified it in ./soco/discovery.py 
and in ./build/lib/soco/discovery.py and did another install. If we need 
further tests. Which one is the file I should edit? the on in soco or in 
build?

**Comment by marcelser** [comment] 2016-05-30 13:27
Hi Lawrence,

I fixed it. Although I'm not a python programmer I've been perl 
programming for +10 years. So I tried to read the code and it was just 
an indentation problem.

The _LOG.info statement must be indented, because addresses is only 
initialized in the else block. But the _LOG statement is outside the if 
block and if we pass in interface_addr it fails. The problem is:

I still get 'None' as response. I hoped that the master branch is fixed 
in that regards but obviously it's still broken. Any ideas on how to fix it?

BTW: How can I set the logvlevel to debug and where are the _LOG 
statements printed to?

Best regards,

Marc

**Comment by lawrenceakka** [comment] 2016-05-31 18:37
@marcelser I have committed a fix for the indentation problem (thanks for tracking that down) and the bug I spotted.

I am not sure why discovery was not working after May 11. Is your script long-running (i.e. did you start it before 11 May, and leave it running). Have you changed your Sonos network at all since then (adding/removing devices etc)?

Lawrence

**Comment by marcelser** [comment] 2016-06-01 00:27
Thanks for committing the fixes.

The Script is not long running. It's running once every night as cronjob and creates/checks a group of 3 Sonos speakers to make sure when the alarm goes off (where you can choose to also play it on grouped devices)  the grouped speakers are always the same ones. So any changes to groups that were made during the day are reset to the defined set.

As it runs as cronjob I get the output. And in the e-mail of 11th may output was ok and starting with 12th may discover started returning 'None'. I checked the install log, no packages were installed/updated between that date. Also I didn't change anything in my sonos network.

So to me it remains a mystery.

Best regards

Marc

Am 31. Mai 2016 20:37:48 MESZ, schrieb Lawrence Akka <notifications@github.com>:
>@marcelser I have committed a fix for the indentation problem (thanks
>for tracking that down) and the bug I spotted.
>
>I am not sure why discovery was not working after May 11. Is your
>script long-running (i.e. did you start it before 11 May, and leave it
>running). Have you changed your Sonos network at all since then
>(adding/removing devices etc)?
>
>Lawrence
>
>
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/SoCo/SoCo/issues/384#issuecomment-222780366

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit Kaiten Mail gesendet.

**Comment by marcelser** [comment] 2016-06-02 06:15
Guess what,

The error is back. It only worked for a very short time

Best regards,

Marc

**Comment by lawrenceakka** [comment] 2016-06-02 08:15
@marcelser I is difficult for me to debug because I cannot reproduce the problem here, but I think I have an idea.  Please can you try the following, and post the output:

```python
import soco
import logging
logging.basicConfig()
logging.getLogger('soco').setLevel(logging.INFO)

import soco.config
soco.config.CACHE_ENABLED = False

devices = soco.discover()
print (devices)
```

**Comment by marcelser** [comment] 2016-06-02 13:11
@lawrenceakka 

Interesting. Did work on the first try. Here's the output:
INFO:soco.discovery:Sending discovery packets on default interface and ['127.0.0.1', '192.168.10.50']
INFO:soco.services:Sending GetZoneGroupState None to 192.168.10.152
INFO:soco.services:Received status 200 from 192.168.10.152
{SoCo("192.168.10.114"), SoCo("192.168.10.226"), SoCo("192.168.10.152"), SoCo("192.168.10.251"), SoCo("192.168.10.233")}

**Comment by lawrenceakka** [comment] 2016-06-02 14:09
Its the log from a time when it doesn't work that I need!!  There is no cache involved here - I suspect that it is something to do with your network config.

**Comment by marcelser** [comment] 2016-06-02 14:13
I see. I included the stuff in my script that runs daily. When it breaks next time I will post the log output

**Comment by rleeden** [comment] 2016-08-26 13:37
In case anybody else comes across this post after searching for SoCo discover() returnng None, I too struggled with this for a while. It used to work fine with me, until I made some network changes including changing my router. It turns out that my new router struggles with UDP multicast packets to wireless devices. So if all your Sonos devices are wireless it's worth plugging one in to an ethernet port if you can and then run a discover again. 

This worked for me, although having a Sonos device permanently plugged in is not really a suitable solution for me at the moment. But I can make do without runnning discover() so not a big deal.

**Comment by KennethNielsen** [comment] 2017-01-28 22:30
There has been some updates to discover code etc. Can anyone confirm whether this is still an issue.

**Comment by ph1l** [comment] 2017-03-29 00:17
This issue is present for me:
```
elektron@x61s:~/code/SoCo$ python test.py 
INFO:soco.discovery:Sending discovery packets on [<socket._socketobject object at 0x7f0cd54866e0>, <socket._socketobject object at 0x7f0cd5486750>]
None
```

**Comment by KennethNielsen** [comment] 2017-03-30 15:13
@ph1l which version of the code are you using. I believe the fixes has not been released yet, so you will need to try against the development version. To find the version do

```python
import soco
print(soco.__version_)
```

**Comment by ph1l** [comment] 2017-03-30 18:53
```
0.12+
```

**Comment by readingtype** [comment] 2017-03-31 14:01
Here is my report, following @lawrenceakka's code of 2016-06-02 above, in Python 2, with a Sonos PLAY:1, version 7.1. I've tried this both wireless and wired.
```
...
devices = soco.discover()
print (devices)
INFO:soco.discovery:Sending discovery packets on ['0.0.0.0', '0.0.0.0']
None
print soco.__version__
0.12
```
I can pass the interface_addr argument to discover() but with no difference in the result.

**Comment by andrew-1** [comment] 2017-04-09 07:33
This may or may not be helpful but this morning soco.discover() started returning None on my raspberry pi after a system restart. I realised that I had an openvpn connection configured to run at boot, that wasn't running when soco.discover() was working yesterday. When I killed the vpn connection soco.discover() started working again.

**Comment by KennethNielsen** [comment] 2017-04-13 08:09
@readingtype I remember that there was talk about using a third party library to find the interfaces, which I would have though would solve it, so I'm curious about what you mean when you say that it also does not work when you try that. Can you please post code in debug mode as above?

**Comment by readingtype** [comment] 2017-04-13 10:49
@KennethNielsen The thing I did was take the appropriate IP address of my machine (the wlan), found using ifconfig, and use that as the value of the interface_addr argument:

```
print soco.discover(interface_addr="192.168.0.136")
INFO:soco.discovery:Sending discovery packets on default interface
None

```
If I skip discovery I can communicate with the Sonos player I have on my wireless network, already knowing its IP address (log output omitted):

```
player = soco.SoCo("192.168.0.193")
player.player_name
'Roving player'
```

**Comment by KennethNielsen** [comment] 2017-04-13 11:19
@readingtype ah, but your version string mentions 0.12. Are you running of the released version? As mentioned earlier there was some improvements done to discovery, which has not yet been released. Can you try it with the development version directly from github?

**Comment by KennethNielsen** [comment] 2017-04-13 11:23
@ph1l can you try and manually feed it the ip-adresses to use for discovery, as found e.g. by the netifaces module, as documented here: http://docs.python-soco.com/en/latest/api/soco.discovery.html#soco.discovery.discover in the Note box?

**Comment by readingtype** [comment] 2017-04-13 15:32
@KennethNielsen I've just pulled and run it:

```
(soco_test)ben@buurlap02:~/code/py/SoCo$ python test.py 
Version 0.12+
INFO:soco.discovery:Sending discovery packets on [<socket._socketobject object at 0x7f06170a5f30>, <socket._socketobject object at 0x7f06170a5fa0>]
None
```
test.py is 

```
import logging
import soco
print "Version %s" % soco.__version__
logging.basicConfig(level=logging.DEBUG)
print soco.discover()

```
pip freeze says

```
(soco_test)ben@buurlap02:~/code/py/SoCo$ pip freeze
requests==2.13.0
xmltodict==0.10.2
```

Python in this virtualenv is 2.7.12.

**Comment by readingtype** [comment] 2017-04-13 15:52
The discovery message is, I believe, this code in discovery.py:

```
    PLAYER_SEARCH = dedent("""\
        M-SEARCH * HTTP/1.1
        HOST: 239.255.255.250:1900
        MAN: "ssdp:discover"
        MX: 1
        ST: urn:schemas-upnp-org:device:ZonePlayer:1
        """).encode('utf-8')
    MCAST_GRP = "239.255.255.250"
    MCAST_PORT = 1900

```
Wireshark shows me the messages on my 192.168.0.136 interface (wlan) from running discover(). Here's one pretty-printed:

> 
> Internet Protocol Version 4, Src: 192.168.0.136, Dst: 239.255.255.250
> User Datagram Protocol, Src Port: 56921 (56921), Dst Port: 1900 (1900)
> Hypertext Transfer Protocol
>     M-SEARCH * HTTP/1.1\n
>         [Expert Info (Chat/Sequence): M-SEARCH * HTTP/1.1\n]
>             [M-SEARCH * HTTP/1.1\n]
>             [Severity level: Chat]
>             [Group: Sequence]
>         Request Method: M-SEARCH
>         Request URI: *
>         Request Version: HTTP/1.1
>     HOST: 239.255.255.250:1900\n
>     MAN: "ssdp:discover"\n
>     MX: 1\n
>     ST: urn:schemas-upnp-org:device:ZonePlayer:1\n
> 

I've also recorded some on the same interface that explicitly state they're from Google Chrome.

**Comment by ph1l** [comment] 2017-04-14 02:36
@KennethNielsen 

```
elektron@yoga:~/code/SoCo$ cat test.py 
from netifaces import interfaces, AF_INET, ifaddresses
import soco
import logging
import soco.config

print("SoCo Version: {}".format(soco.__version__))

logging.basicConfig()
logging.getLogger('soco').setLevel(logging.DEBUG)

soco.config.CACHE_ENABLED = False

for interface in interfaces():
  print("interface: {}".format(interface))
  if interface == "lo":
    print("  skipping")
    continue
  addrs = ifaddresses(interface)
  for k in addrs.keys():
    for addr in addrs[k]:
      address = addr['addr']
      print("  {}".format(address))
      try:
        devices = soco.discover(interface_addr=address)
        print ("    {!r}".format(devices))
      except:
        print ("    ERR")
        pass

elektron@yoga:~/code/SoCo$ python test.py
SoCo Version: 0.12+
interface: lo
  skipping
interface: wlp4s0
  f8:16:54:09:97:5a
    ERR
  10.0.65.119
INFO:soco.discovery:Sending discovery packets on default interface
    None
  fe80::fa16:54ff:fe09:975a%wlp4s0
    ERR
elektron@yoga:~/code/SoCo$ git log | head -1
commit 5ceb38455fb6da6cc03af8444b1e1ed9ff9aa815
```

**Comment by muammar** [comment] 2017-04-29 14:40
I can confirm this problem, too. Having a vpn running makes `soco.discover()` to return `None`. Do you have any plan to support discovery when using vpns?

**Comment by ghcs27** [comment] 2018-05-23 14:37
Since this is quite old and seems to address multiple problems, some of which have been fixed, I'm closing this now. If you have this problem, please look at #619 or open a new issue.

**Closed by ghcs27** 2018-05-23 14:37 UTC
Labels: Bug, Confirmed, Needs info
