### ISSUE TITLE
discovery does not work on ubuntu Ubuntu 18.04.2 LTS

### ISSUE THREAD

**Issue by seth4618** [SoCo/SoCo#669] opened 2019-06-17 15:53 UTC
I can connect to speaker if I specify the IP, e.g., `player = soco.SoCo("192.168.1.195")` works fine.  However, both `soco.discover()` and `soco.discover(interface_addr='192.168.1.191')` return None.

Is there a work around so I can use socos inside mkchromecast?  Or, is there a fix?  Am happy to provide more info, just let me know what you need.

I have tried both version 0.11 and 0.17

**Comment by tksunw** [comment] 2019-06-18 04:00
i had the same problem on ubuntu 18.04.02, but it was fixed by 0.17.    What version of python are you using inside mckchromecast (i'm not familiar with that)?  

SoCo 0.17 works for me with both python2 and python3 as packaged by the maintainers.  No custom builds here.

```
tim@chaos:~$ uname -a
Linux chaos 4.15.17-2-pve #1 SMP PVE 4.15.17-10 (Tue, 22 May 2018 11:15:44 +0200) x86_64 x86_64 x86_64 GNU/Linux

tim@chaos:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic

tim@chaos:~$ python3
Python 3.6.8 (default, Jan 14 2019, 11:02:34)
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import soco
>>> soco.__file__
'/usr/local/lib/python3.6/dist-packages/soco/__init__.py'
>>> soco.__version__
'0.17'
>>> soco.discover()
{SoCo("192.168.1.108"), SoCo("192.168.1.164"), SoCo("192.168.1.121"), SoCo("192.168.1.179"), SoCo("192.168.1.157"), SoCo("192.168.1.166"), SoCo("192.168.1.167"), SoCo("192.168.1.169")}
>>> quit()

tim@chaos:~$ python2
Python 2.7.15+ (default, Nov 27 2018, 23:36:35)
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import soco
>>> soco.__file__
'/usr/local/lib/python2.7/dist-packages/soco/__init__.pyc'
>>> soco.__version__
'0.17'
>>> soco.discover()
/usr/local/lib/python2.7/dist-packages/soco/services.py:686: FutureWarning: The behavior of this method will change in future versions.  Use specific 'len(elem)' or 'elem is not None' test instead.
  value_list_elt = state.find('{}allowedValueList'.format(ns))\
set([SoCo("192.168.1.164"), SoCo("192.168.1.167"), SoCo("192.168.1.169"), SoCo("192.168.1.166"), SoCo("192.168.1.179"), SoCo("192.168.1.108"), SoCo("192.168.1.157"), SoCo("192.168.1.121")])
>>> quit()
```

It's interesting that you can interact with speakers that you explicitly specify.  Is it possible that broadcast traffic is being blocked on your network?

**Comment by KennethNielsen** [comment] 2019-06-18 19:42
Hi @seth4618 and @tksunw 

Did you upgrade your speakers as well? ``discovery`` was changed for version 0.18, to accommodate a change in the Sonos API. But the change in SoCo is backwards incompatible, as outlined in the release notes: http://docs.python-soco.com/en/latest/releases/0.17.html)

Regards Kenneth

**Comment by seth4618** [comment] 2019-06-20 01:02
@KennethNielsen 

My speakers are upgraded, App shows: 

```
version 10.2 (build 50165071) 
Hardware version 1.20.1.6-1
Series ID: A200
```

@tksunw 

As for broadcast traffic being blocked, I am not sure how to test that.  Any ideas?

**Comment by seth4618** [comment] 2019-06-20 20:05
One thing that might help, the player I get if I give an explicit IP address is NOT in any group.  It is not a coordinator.  But I only have the one speaker.  (So, for example, it won't let me play_uri)

**Comment by tksunw** [comment] 2019-06-20 20:30
@seth4618  - your speaker setting looks just like one of my Play:1 speakers.  

As for the broadcast traffic being blocked, that's the only think I can think of that would prevent SoCo from doing discovery.   Discovery is done using a UDP multicast datagram.   What kind of router do you have?  

Or, come to think of it, it could be a permissions problem.  If you run python as root, and import soco, and manually run a soco.discover(), does that work?

**Comment by seth4618** [comment] 2019-06-21 03:02
running as sudo doesn't help.  Here is a transcript of a python sessions.  Notice I can connect directly if I use the IP address.  The block of info near the end if a print I inserted in the src/core.py right after the network returns data when connecting.  As you can see, I am definitely using version 0.17

```
prompt> sudo /home/seth/.virtualenvs/sonos/bin/python
Python 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from soco import discovery
>>> discovery.discover()
>>> discovery.discover(include_invisible=True)
>>> from netifaces import interfaces, AF_INET, ifaddresses
>>> data = [ifaddresses(i) for i in interfaces()]
>>> [d[AF_INET][0]['addr'] for d in data if d.get(AF_INET)]
['127.0.0.1', '192.168.1.191']
>>> discovery.discover(include_invisible=True, interface_addr='192.168.1.191')
>>> discovery.discover(include_invisible=True, interface_addr='127.0.0.1')
>>> discovery.__dict__.keys()
dict_keys(['__name__', '__doc__', '__package__', '__loader__', '__spec__', '__file__', '__cached__', '__builtins__', 'unicode_literals', 'logging', 'socket', 'select', 'dedent', 'time', 'struct', 'config', 'really_utf8', '_LOG', 'discover', 'any_soco', 'by_name'])
>>> import soco
>>> soco.__dict__.keys()
dict_keys(['__name__', '__doc__', '__package__', '__loader__', '__spec__', '__path__', '__file__', '__cached__', '__builtins__', 'logging', 'config', 'compat', 'exceptions', 'xml', 'utils', 'data_structures', 'discovery', 'soap', 'music_services', 'data_structures_entry', 'groups', 'music_library', 'cache', 'events_base', 'events', 'services', 'core', 'SoCo', 'discover', 'SoCoException', 'UnknownSoCoException', '__author__', '__version__', '__website__', '__license__', '__all__'])
>>> soco.__version__
'0.17'
>>> soco.discover()
>>> from soco import SoCo
>>> p = SoCo('192.168.1.195')
>>> p.player_name
b'<ZoneGroupState><ZoneGroups><ZoneGroup Coordinator="RINCON_347E5CC2374C01400" ID="RINCON_347E5CC2374C01400:3821010049"><ZoneGroupMember UUID="RINCON_347E5CC2374C01400" Location="http://192.168.1.195:1400/x
ml/device_description.xml" ZoneName="Kitchen" Icon="x-rincon-roomicon:kitchen" Configuration="1" SoftwareVersion="50.1-65071" SWGen="1" MinCompatibleVersion="49.0-00000" LegacyCompatibleVersion="36.0-00000" BootSeq="2" TVConfigurationError="0" HdmiCecAvailable="0" WirelessMode="1" WirelessLeafOnly="0" HasConfiguredSSID="1" ChannelFreq="2422" BehindWifiExtender="0" WifiEnabled="1" Orientation="0" RoomCalibrationState="1" SecureRegState="3" VoiceConfigState="0" MicEnabled="0" AirPlayEnabled="0" IdleState="1" MoreInfo=""/></ZoneGroup></ZoneGroups><VanishedDevices></VanishedDevices></ZoneGroupState>'
'Kitchen'
```

I am using a netgear N900 router.   I looked over the config and there is nothing about blocking broadcast.   Any suggestions before I start digging into the discovery code?

**Comment by amelchio** [comment] 2019-06-21 06:16
I worked a bit on discovery in my pysonos fork, you could first see if I already fixed your issue:
```
$ python -c "import pysonos; print(pysonos.discover(all_households=True))"
```

**Comment by seth4618** [comment] 2019-06-22 20:11
> I worked a bit on discovery in my pysonos fork, you could first see if I already fixed your issue:
> 
> ```
> $ python -c "import pysonos; print(pysonos.discover(all_households=True))"
> ```

Sadly, no difference - still None

**Comment by amelchio** [comment] 2019-06-23 07:27
Okay. Well, at least you will then not be duplicating work if you do dive into the discovery code :-)

**Comment by unconfigured** [comment] 2019-06-30 12:15
Hi, I've had the same issue. This seems to be also related to: https://github.com/SoCo/SoCo/issues/651.

The problem is in parse_zone_group_member (core.py). The call to GetZoneGroupState returns an XML which is than searched for all "ZoneGroup" entries. But the "ZoneGroup" entries are now child of a "ZoneGroups" element and thus not found. For me changing the "group_element" loop from `tree.findall('ZoneGroup')` to `tree.find('ZoneGroups').findall('ZoneGroup')` fixes the discovery problem.

**Comment by seth4618** [comment] 2019-06-30 16:14
I am having a much more basic issue.  By using tcpdump I see that the speaker is responding to my multicast, but the select in `discovery.py` NEVER returns that there is any data.  I am using python `Python 3.6.7 (default, Oct 22 2018, 11:32:17) `   I added a print to see which socket I was sending on and it shows:

```
Creating socket with 192.168.1.191
Sending: <socket.socket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=17, laddr=('0.0.0.0', 0)>
x: 119
Sending: <socket.socket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=17, laddr=('0.0.0.0', 45916)>
x: 119
Sending: <socket.socket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=17, laddr=('0.0.0.0', 45916)>
```

The corresponding tcpdump is:

```
12:08:52.486069 IP (tos 0x0, ttl 4, id 39231, offset 0, flags [DF], proto UDP (17), length 147)
    seth-ThinkPad-T480s.fios-router.home.45916 > 239.255.255.250.1900: UDP, length 119
E....?@...*..........\.l....M-SEARCH * HTTP/1.1
HOST: 239.255.255.250:1900
MAN: "ssdp:discover"
MX: 1
ST: urn:schemas-upnp-org:device:ZonePlayer:1

12:08:52.486124 IP (tos 0x0, ttl 4, id 39232, offset 0, flags [DF], proto UDP (17), length 147)
    seth-ThinkPad-T480s.fios-router.home.45916 > 239.255.255.250.1900: UDP, length 119
E....@@...*..........\.l....M-SEARCH * HTTP/1.1
HOST: 239.255.255.250:1900
MAN: "ssdp:discover"
MX: 1
ST: urn:schemas-upnp-org:device:ZonePlayer:1

12:08:52.486153 IP (tos 0x0, ttl 4, id 39233, offset 0, flags [DF], proto UDP (17), length 147)
    seth-ThinkPad-T480s.fios-router.home.45916 > 239.255.255.250.1900: UDP, length 119
E....A@...*..........\.l....M-SEARCH * HTTP/1.1
HOST: 239.255.255.250:1900
MAN: "ssdp:discover"
MX: 1
ST: urn:schemas-upnp-org:device:ZonePlayer:1

12:08:52.767003 IP (tos 0x0, ttl 64, id 26390, offset 0, flags [DF], proto UDP (17), length 524)
    SonosZP.fios-router.home.55229 > seth-ThinkPad-T480s.fios-router.home.45916: UDP, length 496
E...g.@.@.L............\....HTTP/1.1 200 OK
CACHE-CONTROL: max-age = 1800
EXT:
LOCATION: http://192.168.1.195:1400/xml/device_description.xml
SERVER: Linux UPnP/1.0 Sonos/50.1-65071 (ZPS12)
ST: urn:schemas-upnp-org:device:ZonePlayer:1
USN: uuid:RINCON_347E5CC2374C01400::urn:schemas-upnp-org:device:ZonePlayer:1
X-RINCON-HOUSEHOLD: Sonos_iyYUTzAZjUSJDsaBadOOK2GQFP
X-RINCON-BOOTSEQ: 2
X-RINCON-WIFIMODE: 1
X-RINCON-VARIANT: 2
HOUSEHOLD.SMARTSPEAKER.AUDIO: Sonos_iyYUTzAZjUSJDsaBadOOK2GQFP.RmcmkwBQ35AxWPa_fNdS


12:08:57.773433 ARP, Ethernet (len 6), IPv4 (len 4), Request who-has seth-ThinkPad-T480s.fios-router.home tell SonosZP.fios-router.home, length 28
........4~\.7L..............
12:08:57.773469 ARP, Ethernet (len 6), IPv4 (len 4), Reply seth-ThinkPad-T480s.fios-router.home is-at 50:76:af:2e:f4:8c (oui Unknown), length 28
........Pv........4~\.7L....
```

Any ideas?

**Comment by tagdara** [comment] 2019-07-14 21:42
I'm not sure if it's related to this problem or new to 10.3 because I was on vacation, but I came home to find that discovery no longer worked for me either.

Raspbian Stretch and Python 3.5.3 with Soco .17.   I made no changes - everything was fine on June 28th, but it seems to have failed around July 11 which is likely when the system got upgraded to 10.3.  As usual the extensive release notes don't mention breaking discovery directly, but it does point out new support for Control-4 SDDP.

I have official controllers using Windows and IOS and they can all do discovery and work normally, so it would not appear to be network related.

**Comment by KennethNielsen** [comment] 2019-11-06 20:46
@seth4618 is this still a problem for you and did you try using netifaces to get a list of ip-adresses to try as current as mentioned in the doc string https://github.com/SoCo/SoCo/blob/master/soco/discovery.py#L47

**Comment by Sonosy** [comment] 2020-02-07 11:13
Apologies, test message
Just joined Github, commented a cause and solution to this but it seems to have lost it

**Comment by Sonosy** [comment] 2020-02-07 11:24
I had the same problem on Windows, for me
`socket.gethostbyname(socket.getfqdn())`
returned
'169.254.52.68'
whereas
`socket.gethostbyname_ex(socket.getfqdn())[2]`
returned
['169.254.52.68', '192.168.56.1', '192.168.77.1', '192.168.15.1', '192.168.1.12']
The .68 is an Npcap loopback device (ie wrong), my interface is at .12
I fount a solution at [stackoverflow](https://stackoverflow.com/questions/166506/finding-local-ip-addresses-using-pythons-stdlib/25850698#25850698)
which basically uses
```
s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
s.connect(('8.8.8.8', 1))  # connect() for UDP doesn't send packets
local_ip_address = s.getsockname()[0]
```
soco.discover() uses 
`socket.gethostbyname(socket.getfqdn())`

I changed my local discover.py to
```
    _sockets = []
    # Use the specified interface, if any
    if interface_addr is not None:
        try:
            address = socket.inet_aton(interface_addr)
        except socket.error:
            raise ValueError("{0} is not a valid IP address string".format(
                interface_addr))
        _sockets.append(create_socket(interface_addr))
        _LOG.info("Sending discovery packets on %s", interface_addr)
    else:
        # Find the local network address using a couple of different methods.
        # Create a socket for each unique address found, and one for the
        # default multicast address
        addresses = set()
        try:
            skt = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
            #connect to a known address. 8.8.8.8 is a Google dns
            skt.connect(('8.8.8.8', 1))  # connect() for UDP doesn't send packets
            addresses.add(skt.getsockname()[0])
        except socket.error:
            pass
       
        try:
            addresses.add(socket.gethostbyname(socket.gethostname()))
        except socket.error:
            pass
        try:
            addresses.add(socket.gethostbyname(socket.getfqdn()))
        except socket.error:
            pass
        for address in addresses:
            try:
                _sockets.append(create_socket(address))
            except socket.error as e:
                _LOG.warning("Can't make a discovery socket for %s: %s: %s",
                             address, e.__class__.__name__, e)
        # Add a socket using the system default address
        _sockets.append(create_socket())
        # Used to be logged as:
        # list(s.getsockname()[0] for s in _sockets)
        # but getsockname fails on Windows with unconnected unbound sockets
        # https://bugs.python.org/issue1049
        _LOG.info("Sending discovery packets on %s", _sockets)

```
It works on Windows and Raspbian...

**Comment by CheapB** [comment] 2020-05-12 15:04
I suspect the issue is you have multiple network adaptors or a complex network setup. I have tested discovery on Windows 10, Raspberry, Chip and Windows server 2008 and it only fails on the windows server and I suspect is is because I have 5 network adaptors and run Microsoft Virtual Network Switch protocol. Do you run any virtual machines on your Ubuntu instance or have multiple NICs?

**Comment by tagdara** [comment] 2020-05-22 23:41
I discovered my problem was actually some upstream network routing that was losing some broadcast traffic, so this is definitely no longer an issue for me.

**Comment by pwt** [comment] 2021-04-03 16:29
Substantial improvements were made to discovery in SoCo v0.21, which should address all of the commonly encountered problems. Hence, I'm going to close this issue.

**Closed by pwt** 2021-04-03 16:29 UTC
