### ISSUE TITLE
Python 2.6/3.2 ongoing support

### ISSUE THREAD

**Issue by lawrenceakka** [SoCo/SoCo#263] opened 2014-11-30 12:27 UTC
From #255 

The new versions of pylint and astroid have dropped support for Python 2.6 (and presumably also for python 3.2). At the moment, we have pinned to old versions in requirements-dev.txt. We will have to decide what to do about our own Python 2.6 support going forward. One option may be to have Travis use different versions of pylon etc for Py2.6, but this seems a bit messy.

**Comment by KennethNielsen** [comment] 2015-01-16 07:01
Hi @robwebset

I just wanted to hear if you have had a chance to open a kodi bug report about this or possibly chiming in on an existing one?

**Comment by KennethNielsen** [comment] 2015-01-16 07:21
In any case. I have not seen any comments against dropping 3.2. Anyone?

I have been looking for a source of information about which version of python are available via the packaging system in the supported version of different Linux distributions (and Mac OS for that matter) but my google foo seems insufficient :(

Basically I was looking for documentation for whether it would be o.k. drop 3.0-3.2.

**Comment by robwebset** [comment] 2015-01-16 08:10
@KennethNielsen Unfortunately there are lots of requests posted that ask for upgrading it in Kodi/XBMC however none seem to get actioned - I guess it's a waiting game :(

**Comment by KennethNielsen** [comment] 2015-01-16 12:14
@robwebset Yeah ok, but I guess what I was wondering was whether any of these requests has made it clear that it is more than a convinience question. Because, I can (somewhat) understand, that the Kodi devs, are unwilling to work on it, if it is just because people prefer something newer, but if anyone says, you are going to loose this plugin if nothing happens, that might be a different matter.

**Comment by robwebset** [comment] 2015-01-16 13:21
@KennethNielsen The problem is, the core Kodi developers really don't care about the addons too much - their answer is petty much "I don't care if you addon doesn't work - I don't use it myself"

**Comment by KennethNielsen** [comment] 2015-01-17 10:16
@robwebset That sucks, but in that case, I would also feel less responsible to the users of Kodi. To put in bluntly, if their developers don't care about their add-on system, why should we?

Except of course, because you still want to be able to use SoCo *grumble*.

Hmm, I'm contemplating whether at the point where we have good music service support (which in my mind is the 1 big item we are missing), we should make a 2.6 branch. We could then, provided someone is willing to do the work (that would be you), backport important new features and bug fixes and release a separate SoCo2.6 package from there. In any case, such consideration can wait until we are actually ready to branch of.

With regards to the actual problem, namely that maintaining 2.6 test runs and linting will keep us on old versions of the test and linting software, an alternative solution could be, to remove the 2.6 from the automatic tests and say that having a release be labelled as supporting 2.6 (in pypi) would then rely on someone (again, that would be you) running the test suite on python 2.6 and letting people know that it passes. The only downsides that I can see to that approach, is that you may have to fix 2.6 incompatibility issues in code you didn't write and that @stefankoegl will have to toggle 2.6 on and of for each release depending on whether you test the release, and I don't know how much trouble that is.

**Comment by robwebset** [comment] 2015-01-17 14:37
@KennethNielsen I think we have been down this road before - when I originally supplied a pull request for 2.6 support I recall that you didn't want it added - but everyone else agreed, so it went in.

I don't see why it should be pulled now (especially as I think the Kodi addon is most probably the biggest free opensource project that uses SoCo at the moment) I fail to see what has changed that would really force this support to be pulled just a few months since it was added.

**Comment by KennethNielsen** [comment] 2015-01-18 09:54
@robwebset If you will notice I was merely discussing alternatives. The first alternative would branch of and essentially pull support at some future point in time, i.e. **not now**. The second alternative would maintain support, but simply depend on manual testing for support to be included in the release.

With regards to previous decisions, yes, we have had this discussion recently, and I did then, and will continue to respect the groups decision. However, with regards to what have changed, well;

 * Several of tools that we depend on, have now finally pulled the plug on support for this 6+ year old version of python, a tendency which I do not think will slow down, which will make it ever increasingly more difficult to maintain properly
 * And of lesser importance, we then now learn, that the main user of the 2.6 support is the plugin system of a program that don't really care about its plugins to begin with, which kind of suck (and also, as far as I understand, did the whole plugin system wrong to begin with, essentially including python in the application, instead of including the application in python).

Do not misunderstand me (no need to get defensive), I care about this project, and of maintaining it in a somewhat professional way, so that users know they can depend on it, so obviously we should not go and add and pull support for python versions on a whim. We decided to add it, and I stand by that, and so I don't think we should remove the support again before it becomes necessary or the need for it has vanished. **But** we do need to reconsider this position when new stuff happens and that so happens to be pretty quickly.

PS: Just on a side note. As I remember the discussion about adding 2.6 support in the first place, at least one of the proponents was also suggesting that the support would be time limited and that the purpose would be to give you a **newer** version to work with (not indefinite support), which is pretty close to my first alternative.

**Comment by stefankoegl** [comment] 2015-01-18 11:44
@robwebset could you point us to the discussions (in mailing lists, bugtrackers, etc) about Kodi's support for recent Python versions?

**Comment by robwebset** [comment] 2015-01-18 11:55
Hi @stefankoegl there are several, hopefully the following link shows some of them:

http://forum.kodi.tv/search.php?action=results&sid=744f012a15d11c7b955a97831ef63650&sortby=&order=desc

The most recent seems to be:

http://forum.kodi.tv/showthread.php?tid=205204

**Comment by stefankoegl** [comment] 2015-01-18 12:11
From the discussion in the last link it sounds like 2.7 would already be supported.

**Comment by robwebset** [comment] 2015-01-18 13:07
@stefankoegl for some OSs, but for others:
Android/ios/osx use 2.6.x

**Comment by stefankoegl** [comment] 2015-01-20 15:51
And which of those do you use?

**Comment by robwebset** [comment] 2015-01-20 15:56
It's not up to me which I use (WIndows as it happens) - but more what other users of the addon use - which can be any of the OSs as I support all of them within Kodi:
http://kodi.wiki/view/Add-on:Sonos

**Comment by KennethNielsen** [comment] 2015-01-22 07:48
@robwebset Can you "declare" in your plugin, which OSs it is supposed to work for?

**Comment by robwebset** [comment] 2015-01-22 07:52
@KennethNielsen I would see no reason to, why would I want to suport less users? At the moment all Kodi users can make use of the Sonos addon.

**Comment by KennethNielsen** [comment] 2015-01-22 07:53
@robwebset Yes, but is it possible?

**Comment by robwebset** [comment] 2015-01-22 07:57
@KennethNielsen it might - I've not looked into it, there is no need, as I support all OSs - and wish to keep it that way

**Comment by robwebset** [comment] 2015-01-29 06:57
Posted a new thread targetting a given release for Kodi Python upgrade:

http://forum.kodi.tv/showthread.php?tid=216598

**Comment by KennethNielsen** [comment] 2015-01-29 14:20
@robwebset Thanks, I see your point about reluctance

**Comment by KennethNielsen** [comment] 2015-07-29 11:46
I suggest we close this and open separate issues about each groups (2.6 and 3.2) as I suspect we will find it much easier so drop early 3 versions than 2.6. That of course will not help us on the pylint issue but at least will get us rid of various annoyances in python 3.2.

**Closed by KennethNielsen** 2015-07-29 11:46 UTC
