### ISSUE TITLE
Spotify music_service search fails - AuthTokenExpired

### ISSUE THREAD

**Issue by Zolmeister** [SoCo/SoCo#428] opened 2016-08-30 20:59 UTC
Seems simple enough, am I doing something incorrectly?

``` python
from soco import SoCo
from soco.music_services import MusicService

device = SoCo("x.x.x.x")
service = MusicService('Spotify')
service.search(category='tracks', term='pinball')
```

```
Traceback (most recent call last):
  File "soco-0.11.1-py3.5.egg/soco/music_services/music_service.py", line 151, in call
  File "soco-0.11.1-py3.5.egg/soco/soap.py", line 310, in call
soco.soap.SoapFault: s:Client.AuthTokenExpired: AuthTokenExpired

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sonos.py", line 10, in <module>
    service.search(category='tracks', term='pinball')
  File "soco-0.11.1-py3.5.egg/soco/music_services/music_service.py", line 715, in search
  File "soco-0.11.1-py3.5.egg/soco/music_services/music_service.py", line 182, in call
soco.exceptions.MusicServiceException: ('AuthTokenExpired', 's:Client.AuthTokenExpired')
```

And changing `Spotify` to `Google Play Music`

```
Traceback (most recent call last):
  File "sonos.py", line 10, in <module>
    service.search(category='tracks', term='pinball')
  File "soco-0.11.1-py3.5.egg/soco/music_services/music_service.py", line 715, in search
  File "soco-0.11.1-py3.5.egg/soco/music_services/music_service.py", line 146, in call
  File "soco-0.11.1-py3.5.egg/soco/music_services/music_service.py", line 111, in get_soap_header
  File "soco-0.11.1-py3.5.egg/soco/services.py", line 181, in _dispatcher
  File "soco-0.11.1-py3.5.egg/soco/services.py", line 408, in send_command
  File "soco-0.11.1-py3.5.egg/soco/services.py", line 469, in handle_upnp_error
soco.exceptions.SoCoUPnPException: UPnP Error 8009 received:  from x.x.x.x
```

**Comment by KennethNielsen** [comment] 2016-09-05 20:24
Hallo @Zolmeister and thanks for reporting this.

@lawrenceakka do you have any input on this?

**Comment by tfriedel** [comment] 2016-10-03 20:23
I have the same problem. With SoundCloud too. TuneIn works though.

**Comment by jrathert** [comment] 2016-10-29 14:55
Same problem here with any relevant call to a Spotify-service. E.g. I do
`    
spotify = MusicService('Spotify')
spotify.search(category='tracks', term='pinball')
meta = spotify.get_media_uri("spotify:track:7HFaTkpIeG0pXINEm7EEG4")
`
and both calls (search, get_media_uri) fail.

Although a bit experienced with programming and using PyCharm, I am not able to fully understand that.

**Comment by KennethNielsen** [comment] 2016-10-29 18:10
Hi guys.

We are seeing a lot of this right now for a large number of music services. My guess (which or more or less specifically mentioned in the traceback of the errors) is that one of the ways Sonos does music service authentication has changed and tha basically all the music services that authenticate that way therefore fails.

If someone wants to help and is up for some internet searching, it is possible that there is already information about this in the Sonos community or with one of the other Sonos driver implementations.

**Comment by lawrenceakka** [comment] 2016-11-06 12:13
Yup - the authentication methods have changed.  I'm on it!

**Comment by jandebeule** [comment] 2016-12-20 19:53
@lawrenceakka : do you have any update on this issue?

**Comment by Hackerjoe** [comment] 2016-12-22 05:41
@lawrenceakka Also have same issue. Any news?

**Comment by cfabric** [comment] 2017-01-13 07:44
Exact same problem with Spotify - happy to help @lawrenceakka in terms of testing / researching etc.

Thanks for looking into it!

**Comment by HughMacdonald** [comment] 2017-02-04 13:52
Just wanted to add a "me too" - just started playing with SoCo, and can't get it to search Spotify. Commenting to ensure I get a notification when there's an update from @lawrenceakka

**Comment by JochenPfeifferHD** [comment] 2017-03-26 14:40
Hi it is the same for me. Any News on this?

**Comment by lawrenceakka** [comment] 2017-03-26 17:34
Time for an update - sorry for the long silence :grin:

Sonos has changed the way in which music service account data can be accessed. It used to be possible to get the necessary info from the players, but it is now encrypted using AES-CBC. Although other third party Sonos controllers have worked out how to get round this and decrypt the info (see [here](https://en.community.sonos.com/advanced-setups-229000/how-to-get-basic-information-about-music-services-31678) for a discussion), I am not sure that it would be right for us to do so in an open source project (though I haven't decided yet).

BUT: 

I have today managed to successfully register a python soco script with Google Play Music. The script requires user interaction (you have to go to a web page and input your Google Play credentials). It may therefore be possible to create a workaround where you run a registration script and then use the returned details to allow SoCo to use third party media services. I suppose the details will change from time to time so it might be necessary to run the registration script again.

Research continues ....

**Comment by relevitt** [comment] 2017-03-26 18:07
Thanks for update. I use Sonos to listen to Spotify (plus downloaded music) and the Spotify API for searches. The main drawback of the change is I can't access Spotify Radio via SoCo.

**Comment by ghcs27** [comment] 2017-03-27 09:50
Now that it's confirmed that this problem pertains to all music services, I'd suggest making one issue for all problems arising from the account data encryption, and closing all the individual issues (#433, #446,  #451) since it's better to have all the information in one place.

**Comment by KennethNielsen** [comment] 2017-03-27 19:24
@ghcs27 it is not all music services. I have a few running that works just fine. As I understand it, it is restricted to those that use OAuth authentication (@lawrenceakka right?) , most significantly Google Play Music and Spotify.

I think a common issue is a good idea, but we should make sure to get the description right.

**Comment by jhaals** [comment] 2017-08-10 11:52
Hi, any updates on this issue?

**Comment by jeantristan** [comment] 2017-09-09 12:50
Got the same issue here too

**Comment by KennethNielsen** [comment] 2017-09-18 13:42
@ghcs27 I do however support the idea of making a meta issue. Do you want to formulate it.

I also think, that we should add something in large bold red letters to the github frontpage, which clearly states, that the issue with these services is due to Sonos changing the authentication method to something that open source projects cannot access and that if people want that to change, they should bug Sonos, not us. I think maybe I will do a PR for that.

**Comment by estwanick** [comment] 2018-01-01 00:02
Experiencing the same issue when calling get_metadata() on Apple Music

**Comment by KennethNielsen** [comment] 2018-01-06 09:57
Closing this issue in favor of #557 to gather information in one place.

**Closed by KennethNielsen** 2018-01-06 09:57 UTC
